import './setupPage';

// register required modules
import './modules/header';
import './modules/footer';
import './modules/map';
import './modules/olMap';
import './modules/menu';
import './modules/toolbox';
import './modules/commons';
import './modules/search';
import './modules/topics';
import './modules/utils';
import './modules/iframe';
import './modules/uiTheme';
import './modules/modal';
import './modules/baseLayer';
import './modules/layerManager';
import './modules/stackables';
import './modules/examples';
import './modules/featureInfo';
import './modules/iconSelect';
import './modules/geoResourceInfo';
import './modules/help';
import './modules/chips';
import './modules/dndImport';
import './modules/auth';
import './modules/elevationProfile';
import './modules/share';
