import './i18n';
import './components/zoomButtons';
import './components/infoButton';
import './components/mapButtonsContainer';
import './components/geolocationButton';
import './components/contextMenu';
import './components/olMap';
import './components/attributionInfo';
import './components/rotationButton';
